/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisplayImage;

import java.awt.Color;
import java.util.LinkedList;
import javax.swing.JFrame;


/**
 *
 * @author Hueletl
 */
public class Board extends javax.swing.JFrame {
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel map;
    private javax.swing.JLabel backGround;                 
    private final LinkedList <Monster> monsters;
    private javax.swing.JLabel frame;
    private javax.swing.JLabel pane;
    private LinkedList <javax.swing.JLabel> outsideTokyo;
    private javax.swing.JButton roll;
    private javax.swing.JLabel curP;//JLabel right before roll button
    private javax.swing.JFrame intoTokyo;
    private boolean turnSelected;
    private Monster curMonster;
    // End of variables declaration  
    
    public Board(LinkedList <Monster> monsters) {
        
        this.map = new javax.swing.JLabel();
        this.backGround = new javax.swing.JLabel();
        this.monsters = monsters; 
//        this.VPs = new LinkedList<>();
//        this.HPs = new LinkedList<>();
//        this.EPs = new LinkedList<>();
//        this.PCs = new LinkedList<>();
        this.outsideTokyo = new LinkedList<>();
        this.roll = new javax.swing.JButton();
        this.curP = new javax.swing.JLabel();
        this.intoTokyo = new javax.swing.JFrame();
        this.turnSelected = false;
        
        
        initComponents();        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        backGround = new javax.swing.JLabel();
        map = new javax.swing.JLabel();
        
        int windowW = 1200;
        int windowH = 820;
        int windowMX = windowW/2;
        
        int x = 800;
        int y = 550;
        int w = 70;
        int h = 50;
        
        //sets current player label right before roll button
        Setting.frame(this, curP, x, y, w, h, false);
        Setting.frameText(curP, "P1", 45, Color.BLACK);
        
        //sets roll button
        x += w;
        w *= 2;  
        Setting.button(this, roll, x, y, w, h, true);
        Setting.buttonText(roll, "ROLL", 45, Color.GREEN);
        roll.addActionListener(this::rollActionPerformed);

        for(int i = 0; i < this.monsters.size(); ++i){
            
            curMonster = monsters.get(i);
            curMonster.setPCurrent(curP);//adds curP to monster
            String name = curMonster.getName();
            String player = Integer.toString(curMonster.getPlayer());
            
            w = 99;
            h = 105;
            x = 1097 - (i * w);
            y = 690;
            
            //monster pLabel
            frame = new javax.swing.JLabel();
            Setting.frame(this, frame, x + 20, y - 40 , 60, 40, false);
            Setting.frameText(frame, "P" + player, 30, Color.YELLOW);
            curMonster.setpLabel(frame);//sets monster pLabel
            
            //monster pIcon
            frame = new javax.swing.JLabel();
            Setting.frame(this, frame, x, y, w, h, true);
            Setting.image(frame,  name +".jpg");
            curMonster.setpIcon(frame);//sets monster pIcon
            
            outsideTokyo.add(frame);
            
            x = this.getX();
            w = 300;
            h = 266;
            
            //finds the location of the monsters frame
            if(i % 2 == 0){
                y = (i/2) * h;         
            }else{
                x = w;
                y = (int)Math.floor(i/2) * h;
            }
            
            // sets the JLabesl inside every monster frame
            int k = 0;
            for(int j = (4*i); j < (4*(i+1)); ++j, ++k){

                int space = 5;
                int paneX = x + space;
                int paneY;
                int paneW = 45;
                int paneH = 40;
                int fontSize = 28;
                
                //finds pane's location
                if(k%2 == 0){
                    paneY = y + ((k/2) * (226-(2*space))) + space;
                }else{
                    paneX = x + 206 + space;
                    paneY = y + ((int)Math.floor(k/2) * (226-(2*space))) + space;
                   
                }
                
                javax.swing.JLabel paneL = new javax.swing.JLabel();
                javax.swing.JLabel paneR = new javax.swing.JLabel();
                
                int newPaneX = paneX + paneW;
                
//                Monster monster = monsters.get(i);
                
                switch (k) {
                    case 0:  //top left
                        Setting.frame(this, paneL, paneX, paneY, paneW, paneH, true);
                        Setting.image( paneL, "VP.png");
                        
                        Setting.frame(this, paneR, newPaneX, paneY, paneW, paneH, false);
                        Setting.frameText(paneR, "0", fontSize, Color.BLUE);
                        curMonster.setVP(paneR);
                        break;
                    case 1:  //top right
                        Setting.frame(this, paneL, paneX, paneY, paneW, paneH, true);
                        Setting.image( paneL, "HP.png");
                        
                        Setting.frame(this, paneR, newPaneX, paneY, paneW, paneH, false);
                        Setting.frameText(paneR, "10", fontSize, Color.RED);
                        curMonster.setHP(paneR);
                        break;
                    case 2:  //bottom left
                        Setting.frame(this, paneL, paneX, paneY, paneW, paneH, true);
                        Setting.image( paneL, "EP.png");
                        
                        Setting.frame(this, paneR, newPaneX, paneY, paneW, paneH, false);
                        Setting.frameText(paneR, "0", fontSize, Color.GREEN);
                        curMonster.setEP(paneR);
                        break;
                    case 3:  //bottom right
                        
                        javax.swing.JButton buttonL = new javax.swing.JButton();
                        Setting.button(this, buttonL, paneX, paneY, paneW, paneH, true);
                        Setting.image( buttonL, "PC.png");
                        
                        Setting.frame(this, paneR, newPaneX, paneY, paneW-space, paneH, true);
                        Setting.frameText(paneR, "0", fontSize, Color.ORANGE);
                        curMonster.setPC(paneR);
                        break;
                    default:
                        break;
                }     
            }
            
            
            
            
            
            //JLabel Monster name
            frame = new javax.swing.JLabel();
            Setting.frame(this, frame, x, y + (h - 100), 300, 40, false);
            Setting.frameText(frame, name, 30, Color.YELLOW);
            
            
            // monster frame
            frame = new javax.swing.JLabel();
            Setting.frame(this, frame, x, y, w, h, true);
            Setting.image(frame,  name +".jpg");
            
           
        }
        
        curMonster = monsters.get(0);
        
        
        Setting.frame(this, map, windowMX, 0, windowMX, windowH-22, true);
        Setting.image(map, "tokyoLand.jpg");
        
        Setting.window(this, backGround, "King Of Tokyo", windowW, windowH, true);

        pack();
    }// </editor-fold>    
    
    public void rollActionPerformed(java.awt.event.ActionEvent evt){
        
//        Setting.window(intoTokyo, 500, 500, false);
//        Setting.windowText(intoTokyo, "Do you want to move\ninto\nTokyo", 45, Color.BLACK, 0, 0, 500, 100, false);
//        
//        javax.swing.JButton yes = new javax.swing.JButton();
//        Setting.button(intoTokyo, yes, 175, 300, 150, 100, false);
//        Setting.buttonText(yes, "YES", 45, Color.BLACK);
//        yes.addActionListener(this::yesActionPerformed);
//        intoTokyo.setVisible(true);
        JFrame rollDice = new RollDice(monsters, curMonster, turnSelected);
        rollDice.setVisible(true);
    }
    
    public void moveInToTokyo(Monster monster){
        int x = 870;
        int y = 60;
        monster.getpLabel().setLocation(x, y);
        monster.getpIcon().setLocation(x-20, y+40);
    }
    
    public void yesActionPerformed(java.awt.event.ActionEvent evt){
        moveInToTokyo(curMonster);
        intoTokyo.setVisible(false);
        
        
    }
}
