/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisplayImage;

import java.awt.*;
import java.awt.image.*;
import java.io.*;
import java.util.LinkedList;
import java.util.Set;
import javax.imageio.*;
import javax.swing.*;

/**
 *
 * @author Hueletl
 */
public class ChooseMonster extends javax.swing.JFrame {

    /**
     * Creates new form ChooseMonster
     */
    public ChooseMonster() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
//    public ChooseMonster(Monster monster) {
//        initComponents();
//        this.setLocationRelativeTo(null);
//        this.monster = monster;
//        String heading = "Player" + Integer.toString( this.monster.getPlayer() );
//        this.Heading.setText(heading);
//        this.Confirm.setVisible(false);
//        this.Cancel.setVisible(false);
//        
//    }

    public ChooseMonster(LinkedList <Monster> monsters, int numPlayers) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.numPlayers = numPlayers;
        this.monsters = monsters;
        int player = monsters.size() + 1;
        this.monster = new Monster("Blank", player);
        String heading = "Player" + Integer.toString( player );
        this.Heading.setText(heading);
        this.Confirm.setVisible(false);
        this.Cancel.setVisible(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Confirm = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Heading = new javax.swing.JLabel();
        Heading1 = new javax.swing.JLabel();
        Character1 = new javax.swing.JButton();
        Character2 = new javax.swing.JButton();
        Character3 = new javax.swing.JButton();
        Character4 = new javax.swing.JButton();
        Character5 = new javax.swing.JButton();
        Character6 = new javax.swing.JButton();
        nameChar1 = new javax.swing.JLabel();
        nameChar2 = new javax.swing.JLabel();
        nameChar3 = new javax.swing.JLabel();
        nameChar4 = new javax.swing.JLabel();
        nameChar5 = new javax.swing.JLabel();
        nameChar6 = new javax.swing.JLabel();
        picChar1 = new javax.swing.JLabel();
        picChar2 = new javax.swing.JLabel();
        picChar3 = new javax.swing.JLabel();
        picChar4 = new javax.swing.JLabel();
        picChar5 = new javax.swing.JLabel();
        picChar6 = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose a Monster");
        setMinimumSize(new java.awt.Dimension(1438, 1001));
        setSize(new java.awt.Dimension(1438, 1001));
        getContentPane().setLayout(null);

        Confirm.setText("Confirm");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(Confirm);
        Confirm.setBounds(1050, 340, 95, 29);

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(1210, 340, 86, 29);

        Heading.setFont(new java.awt.Font("Chalkboard", 1, 36)); // NOI18N
        Heading.setText("Player");
        getContentPane().add(Heading);
        Heading.setBounds(650, 20, 140, 40);

        Heading1.setFont(new java.awt.Font("Chalkboard", 1, 36)); // NOI18N
        Heading1.setText("Choose a Monster");
        getContentPane().add(Heading1);
        Heading1.setBounds(570, 70, 310, 40);

        Character1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Character1.setContentAreaFilled(false);
        Character1.setMaximumSize(new java.awt.Dimension(450, 300));
        Character1.setMinimumSize(new java.awt.Dimension(450, 300));
        Character1.setPreferredSize(new java.awt.Dimension(450, 300));
        Character1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Character1ActionPerformed(evt);
            }
        });
        getContentPane().add(Character1);
        Character1.setBounds(70, 130, 400, 280);

        Character2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Character2.setContentAreaFilled(false);
        Character2.setMaximumSize(new java.awt.Dimension(450, 300));
        Character2.setMinimumSize(new java.awt.Dimension(450, 300));
        Character2.setPreferredSize(new java.awt.Dimension(450, 300));
        Character2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Character2ActionPerformed(evt);
            }
        });
        getContentPane().add(Character2);
        Character2.setBounds(520, 130, 400, 280);

        Character3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Character3.setContentAreaFilled(false);
        Character3.setMaximumSize(new java.awt.Dimension(450, 300));
        Character3.setMinimumSize(new java.awt.Dimension(450, 300));
        Character3.setPreferredSize(new java.awt.Dimension(450, 300));
        Character3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Character3ActionPerformed(evt);
            }
        });
        getContentPane().add(Character3);
        Character3.setBounds(970, 130, 400, 280);

        Character4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Character4.setContentAreaFilled(false);
        Character4.setMaximumSize(new java.awt.Dimension(450, 300));
        Character4.setMinimumSize(new java.awt.Dimension(450, 300));
        Character4.setPreferredSize(new java.awt.Dimension(450, 300));
        Character4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Character4ActionPerformed(evt);
            }
        });
        getContentPane().add(Character4);
        Character4.setBounds(60, 570, 400, 280);

        Character5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Character5.setContentAreaFilled(false);
        Character5.setMaximumSize(new java.awt.Dimension(450, 300));
        Character5.setMinimumSize(new java.awt.Dimension(450, 300));
        Character5.setPreferredSize(new java.awt.Dimension(450, 300));
        Character5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Character5ActionPerformed(evt);
            }
        });
        getContentPane().add(Character5);
        Character5.setBounds(520, 570, 400, 280);

        Character6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Character6.setContentAreaFilled(false);
        Character6.setMaximumSize(new java.awt.Dimension(450, 300));
        Character6.setMinimumSize(new java.awt.Dimension(450, 300));
        Character6.setPreferredSize(new java.awt.Dimension(450, 300));
        Character6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Character6ActionPerformed(evt);
            }
        });
        getContentPane().add(Character6);
        Character6.setBounds(980, 570, 400, 280);

        nameChar1.setFont(new java.awt.Font("Chalkboard", 1, 36)); // NOI18N
        nameChar1.setText("CyberKitty");
        getContentPane().add(nameChar1);
        nameChar1.setBounds(220, 220, 190, 40);

        nameChar2.setFont(new java.awt.Font("Chalkboard", 1, 36)); // NOI18N
        nameChar2.setText("GigaZaur");
        getContentPane().add(nameChar2);
        nameChar2.setBounds(690, 210, 160, 40);

        nameChar3.setFont(new java.awt.Font("Chalkboard", 1, 36)); // NOI18N
        nameChar3.setText("Alienoid");
        getContentPane().add(nameChar3);
        nameChar3.setBounds(1210, 220, 140, 40);

        nameChar4.setFont(new java.awt.Font("Chalkboard", 1, 36)); // NOI18N
        nameChar4.setText("SpacePinguin");
        getContentPane().add(nameChar4);
        nameChar4.setBounds(160, 680, 230, 40);

        nameChar5.setFont(new java.awt.Font("Chalkboard", 1, 36)); // NOI18N
        nameChar5.setText("King");
        getContentPane().add(nameChar5);
        nameChar5.setBounds(700, 710, 80, 40);

        nameChar6.setFont(new java.awt.Font("Chalkboard", 1, 36)); // NOI18N
        nameChar6.setText("MecaDragon");
        getContentPane().add(nameChar6);
        nameChar6.setBounds(1060, 660, 220, 40);

        picChar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonCyberKitty.jpg"))); // NOI18N
        picChar1.setToolTipText("");
        picChar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(picChar1);
        picChar1.setBounds(70, 130, 400, 280);

        picChar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonGigazaur.jpg"))); // NOI18N
        picChar2.setToolTipText("");
        picChar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(picChar2);
        picChar2.setBounds(520, 130, 400, 280);

        picChar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonAlienoid.jpg"))); // NOI18N
        picChar3.setToolTipText("");
        picChar3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(picChar3);
        picChar3.setBounds(970, 130, 400, 280);

        picChar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonSpacePinguin.jpg"))); // NOI18N
        picChar4.setToolTipText("");
        picChar4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(picChar4);
        picChar4.setBounds(60, 570, 400, 280);

        picChar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonKing.jpg"))); // NOI18N
        picChar5.setToolTipText("");
        picChar5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(picChar5);
        picChar5.setBounds(520, 570, 400, 280);

        picChar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonMecaDragon.jpeg"))); // NOI18N
        picChar6.setToolTipText("");
        picChar6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(picChar6);
        picChar6.setBounds(980, 570, 400, 280);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/KingOfTokyo.jpg"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 1438, 1001);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.monsters.add(monster);
        this.numPlayers -= 1; 
        if(numPlayers > 0){
            JFrame chooseMonster = new ChooseMonster(this.monsters, this.numPlayers);
            chooseMonster.setVisible(true);
        }else{
            JFrame board = new Board(this.monsters);
            board.setVisible(true);
        }
    }//GEN-LAST:event_ConfirmActionPerformed

    private void Character1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Character1ActionPerformed
        // TODO add your handling code here:
        setCharacter( nameChar1, Character1);
    }//GEN-LAST:event_Character1ActionPerformed

    private void Character2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Character2ActionPerformed
        // TODO add your handling code here:
        setCharacter( nameChar2, Character2);
    }//GEN-LAST:event_Character2ActionPerformed

    private void Character3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Character3ActionPerformed
        // TODO add your handling code here:
        setCharacter( nameChar3, Character3);
    }//GEN-LAST:event_Character3ActionPerformed

    private void Character4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Character4ActionPerformed
        // TODO add your handling code here:
        setCharacter( nameChar4, Character4);
    }//GEN-LAST:event_Character4ActionPerformed

    private void Character6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Character6ActionPerformed
        // TODO add your handling code here:
        setCharacter( nameChar6, Character6);
    }//GEN-LAST:event_Character6ActionPerformed

    private void Character5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Character5ActionPerformed
        // TODO add your handling code here:
        setCharacter( nameChar5, Character5);
    }//GEN-LAST:event_Character5ActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.Character.setVisible(true);
        this.Confirm.setVisible(false);
        this.Cancel.setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed
    
    private void setCharacter(javax.swing.JLabel nameChar, javax.swing.JButton Character){
        
        int x = Character.getX() + 80;
        int y = Character.getY() + 220;
        this.Confirm.setLocation(x, y);
        
        x += 160;
        this.Cancel.setLocation(x, y);
        
        this.Character = Character;
        this.monster.setPlayer( getContentPane().getComponentZOrder(Character) );
        this.monster.setName(nameChar.getText());
      
        Character.setVisible(false);
        this.Confirm.setVisible(true);
        this.Cancel.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseMonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseMonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseMonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseMonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChooseMonster().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Character1;
    private javax.swing.JButton Character2;
    private javax.swing.JButton Character3;
    private javax.swing.JButton Character4;
    private javax.swing.JButton Character5;
    private javax.swing.JButton Character6;
    private javax.swing.JButton Confirm;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Heading1;
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel nameChar1;
    private javax.swing.JLabel nameChar2;
    private javax.swing.JLabel nameChar3;
    private javax.swing.JLabel nameChar4;
    private javax.swing.JLabel nameChar5;
    private javax.swing.JLabel nameChar6;
    private javax.swing.JLabel picChar1;
    private javax.swing.JLabel picChar2;
    private javax.swing.JLabel picChar3;
    private javax.swing.JLabel picChar4;
    private javax.swing.JLabel picChar5;
    private javax.swing.JLabel picChar6;
    // End of variables declaration//GEN-END:variables

    private Integer numPlayers;
    private LinkedList <Monster> monsters;
    private Monster monster;
    private javax.swing.JButton Character;
}
