/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//import javax.swing.JOptionPane;
package DisplayImage;
import java.awt.Color;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author huele
 */
public class HowManyPlayers extends javax.swing.JFrame {
    // Variables declaration - do not modify                     
    private javax.swing.JLabel backGround;
    private javax.swing.JButton buttonOK;
    private javax.swing.JTextField input;   
    private int numPlayers;
    private LinkedList <Monster> monsters;
    
    // End of variables declaration 

    /**
     * Creates new form HowManyPlayers
     */
    public HowManyPlayers() {
        initComponents();
    }
    public HowManyPlayers(JFrame newGame) {
        initComponents();
        newGame.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        input = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();
        monsters = new LinkedList<>(); 
        int windowW = 1000;
        int windowH = 369;
        int windowMX = windowW/2;
//        numPlayers = 0;

        /*Sets the input field*/
        Setting.inputField(this, input, 32, windowMX - 22, 200, 45, 53);
        input.addActionListener(this::inputActionPerformed);
        
        /*Sets OK button*/
        Setting.button(this, buttonOK, windowMX - 50, 260, 100, 40, false);
        Setting.buttonText(buttonOK, "OK", 30, Color.BLACK);
        buttonOK.addActionListener(this::buttonOKActionPerformed);
//        getRootPane().setDefaultButton(buttonOK); //lets to press button as well as clicking
        
        /*Sets Text on Main Window*/
        Setting.windowText(this, "Enter Number\nOf\nPlayers (2-6)", 30, Color.CYAN, windowMX - 135,90, 270, 30, false);
        /*Sets Main Window*/
        Setting.window(this, backGround, "waterstones.jpg", "Enter Number of Players", windowW, windowH, true);
        
        
        
        pack();
    }// </editor-fold>                        

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        buttonOKActionPerformed(evt);

    }                                     

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String errorMsg = "Please Enter a number between 2 and 6";
        
        try{
            numPlayers = Integer.parseInt(input.getText().trim());
        }catch(NumberFormatException e){
            numPlayers = 0;
        }     
        
        if( (1 < numPlayers) && (numPlayers < 7) ){
            this.setVisible(false);
            JFrame chooseMonster = new ChooseMonster(monsters, numPlayers);
            chooseMonster.setVisible(true);
        }else{
            JOptionPane.showMessageDialog( null, errorMsg );
            numPlayers = 0;
        }
    }                                        

//    /**
//     * @return the numPlayers
//     */
//    public int getNumPlayers() {
//        return numPlayers;
//    }
//
//    /**
//     * @param numPlayers the numPlayers to set
//     */
//    public void setNumPlayers(int numPlayers) {
//        this.numPlayers = numPlayers;
//    }
//    
}
