/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisplayImage;

//import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author huele
 */
public class HowManyPlayers extends javax.swing.JFrame {

    /**
     * Creates new form HowManyPlayers
     */
    public HowManyPlayers() {
        initComponents();
        this.setLocationRelativeTo(null);
        backGround.setBounds(0, 0, this.getWidth(), this.getHeight());//resets the background to the same size as the frame
        ImageResizer.setImage(backGround, "king-of-tokyo-at-waterstones.jpg");//sets the background image
        numPlayers = 0;
        monsters = new LinkedList<Monster>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterNumber = new javax.swing.JLabel();
        of = new javax.swing.JLabel();
        players = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Number of Players");
        setBounds(new java.awt.Rectangle(0, 23, 1000, 369));
        setMaximumSize(new java.awt.Dimension(1000, 369));
        setMinimumSize(new java.awt.Dimension(1000, 369));
        setPreferredSize(new java.awt.Dimension(1000, 369));
        setSize(new java.awt.Dimension(1000, 369));
        getContentPane().setLayout(null);

        enterNumber.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        enterNumber.setForeground(new java.awt.Color(0, 255, 255));
        enterNumber.setText("Enter Number");
        enterNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(enterNumber);
        enterNumber.setBounds(370, 70, 270, 43);

        of.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        of.setForeground(new java.awt.Color(0, 255, 255));
        of.setText("           Of");
        getContentPane().add(of);
        of.setBounds(340, 110, 257, 43);

        players.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        players.setForeground(new java.awt.Color(0, 255, 255));
        players.setText("  Players (2-6)");
        getContentPane().add(players);
        players.setBounds(350, 150, 290, 43);

        input.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        getContentPane().add(input);
        input.setBounds(470, 200, 45, 53);

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOK);
        buttonOK.setBounds(440, 260, 100, 29);

        backGround.setMaximumSize(new java.awt.Dimension(1200, 400));
        backGround.setMinimumSize(new java.awt.Dimension(1200, 400));
        backGround.setPreferredSize(new java.awt.Dimension(1200, 400));
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 500, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_inputActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        // TODO add your handling code here:
        String errorMsg = "Please Enter a number between 2 and 6";
        
        try{
            numPlayers = Integer.parseInt(input.getText().trim());
        }catch(NumberFormatException e){
            numPlayers = 0;
        }     
        
        if( (1 < numPlayers) && (numPlayers < 7) ){
            this.setVisible(false);
            JFrame chooseMonster = new ChooseMonster(monsters, numPlayers);
            chooseMonster.setVisible(true);
        }else{
            JOptionPane.showMessageDialog( null, errorMsg );
            numPlayers = 0;
        }
    }//GEN-LAST:event_buttonOKActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HowManyPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HowManyPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HowManyPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HowManyPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HowManyPlayers().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel enterNumber;
    private javax.swing.JTextField input;
    private javax.swing.JLabel of;
    private javax.swing.JLabel players;
    // End of variables declaration//GEN-END:variables
    
    private int numPlayers;
    private LinkedList <Monster> monsters;

    /**
     * @return the numPlayers
     */
    public int getNumPlayers() {
        return numPlayers;
    }

    /**
     * @param numPlayers the numPlayers to set
     */
    public void setNumPlayers(int numPlayers) {
        this.numPlayers = numPlayers;
    }
    
}
