/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisplayImage;

import java.awt.Color;

/**
 *
 * @author huele
 */
public class MainMenu extends javax.swing.JFrame {
    // Variables declaration - do not modify                     
    private javax.swing.JLabel backGround;
    private javax.swing.JButton battle;
    private javax.swing.JButton exit;
    private javax.swing.JLabel or;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        battle = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        or = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();
        int frameW = 1200;
        int frameH = 800;
        int buttonW = 300;
        int buttonH = 100;
        int buttonX = 800;
        int buttonY = 170;
        
        Setting.button(this, battle, buttonX, buttonY, buttonW, buttonH, true);
        Setting.buttonText(battle, "Battle", 48, Color.RED);
        battle.addActionListener(this::battleActionPerformed);
        
        Setting.button(this, exit, buttonX, buttonY + 200, buttonW, buttonH, true);
        Setting.buttonText(exit, "Exit", 48, Color.RED);
        exit.addActionListener(this::exitActionPerformed);
        
        Setting.window(this, backGround, "KingOfTokyo.jpg", "King of Tokyo", frameW, frameH, true);

        pack();
    }// </editor-fold>                        

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        System.exit(0);
        // TODO add your handling code here:
    }                                    

    private void battleActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        
        new HowManyPlayers().setVisible(true);
        this.setVisible(false);
          
    }                                                      
}

